# Generated by Django 5.2.8 on 2025-12-03 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="course_thumbnails/"
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="video",
            field=models.FileField(blank=True, null=True, upload_to="course_videos/"),
        ),
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.IntegerField(),
        ),
    ]
