# Generated by Django 5.2.8 on 2025-12-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_course_thumbnail_course_video_alter_course_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="duration",
            field=models.CharField(default="Hours", max_length=50),
        ),
        migrations.AddField(
            model_name="course",
            name="instructor",
            field=models.CharField(default="Instructor", max_length=150),
        ),
        migrations.AddField(
            model_name="course",
            name="language",
            field=models.CharField(default="English", max_length=50),
        ),
        migrations.AddField(
            model_name="course",
            name="lessons",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="course",
            name="price",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="course",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
