# Generated by Django 5.2.8 on 2025-12-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_course_duration_course_instructor_course_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="instructor_image",
            field=models.ImageField(blank=True, null=True, upload_to="instructors/"),
        ),
    ]
