# Generated by Django 5.2.8 on 2025-12-03 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_enrolledcourse"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "video",
                    models.FileField(blank=True, null=True, upload_to="lesson_videos/"),
                ),
                ("duration", models.CharField(default="10 min", max_length=20)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_lessons",
                        to="courses.course",
                    ),
                ),
            ],
        ),
    ]
