# Generated by Django 5.2.8 on 2025-12-05 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0008_discussion_reply"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="notes",
            field=models.FileField(blank=True, null=True, upload_to="course_notes/"),
        ),
    ]
