# Generated by Django 5.2.8 on 2025-12-05 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0009_course_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="notes_thumbnail",
            field=models.ImageField(
                blank=True, null=True, upload_to="notes_thumbnails/"
            ),
        ),
    ]
